//! Turn a served profile into the artifacts a workflow consumes: one bazelrc, one set of
//! environment exports, one set of step outputs.
//!
//! ⭐ THE GENERATED BAZELRC IS THE WHOLE INTERFACE. Not a set of flags echoed into a shell
//! array, not `$RBE_ENDPOINT` for a later step to interpolate — a file, passed with
//! `bazel --bazelrc=<path>`. Three reasons, and the third is the one that matters:
//!
//!   1. It is diffable. Two builds that behaved differently can be compared directly.
//!   2. `--announce_rc` prints it into the build log, so the config is IN the evidence.
//!   3. ⛔ A shell variable can be overridden by a later step, silently, and a workflow that
//!      set `RBE_ENDPOINT` at job level would win. A file path cannot be half-overridden:
//!      either Bazel read this file or it did not.
//!
//! ⚠ `--bazelrc` is a STARTUP flag and must precede the command:
//! `bazel --bazelrc=<path> build //...`, never `bazel build --bazelrc=<path>`. Bazel's error
//! for the wrong order names the flag but not the position.

use crate::hostkey;
use crate::protocol::Profile;

/// Everything the Action writes out.
pub struct Rendered {
    /// Contents of the generated bazelrc.
    pub bazelrc: String,
    /// `$GITHUB_ENV` exports, in order.
    pub env: Vec<(String, String)>,
    /// `$GITHUB_OUTPUT` values.
    pub outputs: Vec<(String, String)>,
}

/// Render a profile.
///
/// `token_file` is where the workflow's token-minting step wrote the bearer. ⚠ The variable
/// NAME is derived here from the endpoint host; only the PATH comes from the caller. That
/// asymmetry is deliberate: the path is a local detail, the name is the thing that has to
/// agree with the endpoint and therefore must not be typed by a human.
pub fn render(profile: &Profile, token_file: &str, cred_helper: &str) -> Rendered {
    let mut rc = String::new();
    let f = &profile.facts;
    let r = &profile.recommendations;

    rc.push_str(&format!(
        "# GENERATED BY setup-tbzl — DO NOT EDIT, DO NOT COMMIT.\n\
         #\n\
         # tenant           {}\n\
         # plane            {}\n\
         # protocol         {}\n\
         # config_version   {}\n\
         #\n\
         # ⭐ Every value below was fetched from the platform at runtime. None of it is\n\
         # transcribed into the workflow, which is what makes the endpoint, the scope, the\n\
         # credential-helper host key and the exec-property token unable to drift apart:\n\
         # they have one source.\n\
         #\n\
         # ⭐ This is a VERSIONED recommendation, not a per-build decision. Every build that\n\
         # resolves config_version {} gets these exact bytes. That is what keeps two builds\n\
         # of one commit comparable and a regression bisectable.\n",
        profile.tenant, profile.plane, profile.protocol, profile.config_version,
        profile.config_version,
    ));
    if let Some(basis) = &r.basis {
        rc.push_str(&format!("#\n# basis: {basis}\n"));
    }
    rc.push('\n');

    // ── credential helper ────────────────────────────────────────────────────────────────
    rc.push_str(
        "# ⛔ HOST-KEYED, AND THE HELPER FAILS OPEN. A --credential_helper registered for the\n\
         # wrong host is never invoked for the right one, and the helper answers\n\
         # `{\"headers\":{}}` + exit 0 for any host it has no secret for — so Bazel sends NO\n\
         # Authorization header and the RBE answers UNAUTHENTICATED. The host below is derived\n\
         # from the endpoint above; setup-tbzl also PROBES the helper before the build starts,\n\
         # so an anonymous answer is a step failure rather than 97 failed targets.\n",
    );
    for host in profile.credential_hosts() {
        rc.push_str(&format!(
            "common --credential_helper={host}={cred_helper}\n"
        ));
    }
    rc.push('\n');

    // ── execution ────────────────────────────────────────────────────────────────────────
    if let Some(ex) = &f.execution {
        rc.push_str(&format!("build --remote_executor={}\n", ex.endpoint));
        if !ex.instance_name.is_empty() {
            rc.push_str(&format!(
                "# ⚠ NOT an isolation boundary — Buildbarn routes by PLATFORM, so two tenants\n\
                 # with different instance names share a CAS and share cache entries.\n\
                 build --remote_instance_name={}\n",
                ex.instance_name
            ));
        }
        rc.push_str(
            "# ⛔ BYTE-MATCHED AND PART OF THE ACTION DIGEST. The scheduler string-compares\n\
             # these against what its workers advertise and NEVER fetches the image named. A\n\
             # mismatch does not error: every action queues against an idle fleet. Measured\n\
             # once at 426 slots with ZERO demand and ~4s actions waiting ~40 minutes.\n",
        );
        for (k, v) in &ex.exec_properties {
            rc.push_str(&format!("build --remote_default_exec_properties={k}={v}\n"));
        }
        // ⛔ Emitted unconditionally when it is off, because the DEFAULT is off and an absent
        // flag would leave a repo-level `--remote_local_fallback` in force. Stating it is the
        // only way to be sure the mask is not on.
        if r.remote_local_fallback {
            rc.push_str("build --remote_local_fallback\n");
        } else {
            rc.push_str(
                "# ⛔⛔ THE MASK, EXPLICITLY OFF. With local fallback ON, a wrong exec property\n\
                 # does not queue — the build goes GREEN having run entirely on the runner, the\n\
                 # plane is unused, and the only symptom is that it was slow. Stated rather than\n\
                 # omitted so a repo-level --remote_local_fallback cannot leave it on.\n\
                 build --noremote_local_fallback\n",
            );
        }
    }

    // ── cache ────────────────────────────────────────────────────────────────────────────
    if let Some(c) = &f.cache {
        rc.push_str(&format!("build --remote_cache={}\n", c.endpoint));
    }
    if f.execution.is_none() {
        rc.push_str(
            "# ⭐ THIS PLANE SERVES CACHE ONLY — it declared no execution endpoint. Actions run\n\
             # LOCALLY on the runner and only their results are shared. That is a complete,\n\
             # legitimate answer (it is what roma serves today), and it is stated here so a\n\
             # slow build is not mistaken for a starved fleet.\n",
        );
    }

    // ── recommendations ──────────────────────────────────────────────────────────────────
    rc.push('\n');
    rc.push_str("# ── derived recommendations (config_version above) ──\n");
    if let Some(j) = r.jobs {
        rc.push_str(&format!(
            "# ⚠ Measured wrong in BOTH directions in one day on this estate: a 2-core runner's\n\
             # default of 2 capped REMOTE actions at 2 in flight, and 64 concurrent actions run\n\
             # LOCALLY on that same runner thrashed and OOMed. The right value is a property of\n\
             # where the actions execute, which is why the platform serves it.\n\
             build --jobs={j}\n"
        ));
    }
    if let Some(c) = r.remote_max_connections {
        rc.push_str(&format!(
            "# ⭐ THE BANDWIDTH KNOB. This estate measured 0.46 ms RTT but only 6.3 MB/s per\n\
             # stream, FLAT across four concurrent streams — per-stream throughput did not\n\
             # degrade as streams were added, so latency is not the constraint and aggregate\n\
             # throughput is linear in connection count over the measured range.\n\
             build --remote_max_connections={c}\n"
        ));
    }
    if let Some(t) = r.remote_timeout_seconds {
        rc.push_str(&format!("build --remote_timeout={t}\n"));
    }
    if let Some(d) = &r.remote_download {
        rc.push_str(&format!("build --remote_download_{d}\n"));
    }

    // ── env ──────────────────────────────────────────────────────────────────────────────
    let mut env = Vec::new();
    for host in profile.credential_hosts() {
        // ⭐ DERIVED, NEVER TYPED. See hostkey.rs — this single line is what makes a stale
        // helper key impossible rather than merely discouraged.
        env.push((hostkey::token_file_var(&host), token_file.to_string()));
    }
    // ⭐⭐ THE HOSTS THAT MUST AUTHENTICATE, FROM THE SAME LIST THE HOST KEY CAME FROM.
    //
    // `tomato-bazel/cred-helper` fails open: a miss yields `{"headers":{}}` and exit 0, so
    // Bazel sends no Authorization header and the far end answers UNAUTHENTICATED — a symptom
    // that names the endpoint rather than the credential. `FASTVERK_CRED_REQUIRE` turns a miss
    // into a non-zero exit FOR THESE HOSTS ONLY, which is safe precisely because anonymous is
    // a legitimate answer for a host nobody nominated and never for one somebody did.
    //
    // ⭐ Deriving it here rather than letting a workflow set it is the same property as the
    // token variable: the list of hosts that must authenticate cannot disagree with the list
    // of endpoints, because it IS that list.
    //
    // ⚠ HARMLESS ON AN OLDER HELPER. A binary predating the feature ignores the variable and
    // keeps failing open — at which point `verify::credential_round_trip` is still the check
    // that catches it. Defence in depth, in that order: the probe catches it before the build,
    // this catches it during one.
    let hosts = profile.credential_hosts();
    if !hosts.is_empty() {
        env.push(("FASTVERK_CRED_REQUIRE".into(), hosts.join(",")));
    }
    env.push(("TBZL_CONFIG_VERSION".into(), profile.config_version.clone()));
    env.push(("TBZL_PLANE".into(), profile.plane.clone()));

    let mut outputs = vec![
        ("config-version".to_string(), profile.config_version.clone()),
        ("protocol".to_string(), profile.protocol.clone()),
        ("plane".to_string(), profile.plane.clone()),
        ("runner-label".to_string(), f.runner_label.clone()),
    ];
    if let Some(ex) = &f.execution {
        outputs.push(("endpoint".into(), ex.endpoint.clone()));
    }
    if let Some(j) = r.jobs {
        outputs.push(("jobs".into(), j.to_string()));
    }

    Rendered { bazelrc: rc, env, outputs }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocol::Profile;

    fn profile(json: &str) -> Profile {
        Profile::parse(json.as_bytes()).expect("fixture parses")
    }

    const FULL: &str = r#"{
      "protocol": "tbzl.buildconfig/v1",
      "config_version": "2026-08-05.1",
      "tenant": "savvifi", "plane": "tbzl-build-plane",
      "facts": {
        "runner_label": "tbzl-linux-x64",
        "execution": {
          "endpoint": "grpcs://rbe.tbzl.dev:8980",
          "exec_properties": {"OSFamily": "linux", "container-image": "docker://x/y:z"},
          "advertised_platform": {"OSFamily": "linux", "container-image": "docker://x/y:z"}
        },
        "auth": {"token_url": "https://t/", "scope": "fastverk-api/rbe:build", "issuer": "https://i"}
      },
      "recommendations": {"jobs": 200, "remote_max_connections": 200}
    }"#;

    #[test]
    fn the_helper_host_comes_from_the_endpoint() {
        let r = render(&profile(FULL), "/tmp/tok", "/tmp/cred-helper");
        assert!(r
            .bazelrc
            .contains("common --credential_helper=rbe.tbzl.dev=/tmp/cred-helper"));
        assert!(r
            .env
            .contains(&("FASTVERK_TOKEN_FILE_RBE_TBZL_DEV".into(), "/tmp/tok".into())));
    }

    /// ⛔ The mask must be stated, not omitted — an absent flag leaves a repo-level
    /// `--remote_local_fallback` in force.
    #[test]
    fn local_fallback_is_stated_off_rather_than_left_unsaid() {
        let r = render(&profile(FULL), "/tmp/tok", "/h");
        assert!(r.bazelrc.contains("build --noremote_local_fallback"));
    }

    #[test]
    fn exec_properties_render_deterministically() {
        let a = render(&profile(FULL), "/t", "/h").bazelrc;
        let b = render(&profile(FULL), "/t", "/h").bazelrc;
        assert_eq!(a, b);
        // ⚠ BTreeMap orders by BYTE, not by a case-insensitive name: `O` (0x4F) sorts before
        // `c` (0x63), so `OSFamily` is emitted first. Pinned because the obvious
        // alphabetical reading is the opposite, and a rendering whose order silently flips
        // makes two bazelrc files un-diffable for no reason.
        let ci = a.find("container-image=docker://x/y:z").unwrap();
        let os = a.find("OSFamily=linux").unwrap();
        assert!(os < ci, "properties must be emitted in a stable, byte-ordered sequence");
    }

    /// ⭐ The require-list and the helper host come from ONE call, so they cannot disagree.
    #[test]
    fn the_hosts_that_must_authenticate_are_the_endpoints_themselves() {
        let r = render(&profile(FULL), "/tmp/tok", "/h");
        assert!(r
            .env
            .contains(&("FASTVERK_CRED_REQUIRE".into(), "rbe.tbzl.dev".into())));
    }

    #[test]
    fn config_version_is_recorded_for_the_build_record() {
        let r = render(&profile(FULL), "/t", "/h");
        assert!(r.bazelrc.contains("config_version   2026-08-05.1"));
        assert!(r.env.contains(&("TBZL_CONFIG_VERSION".into(), "2026-08-05.1".into())));
        assert!(r
            .outputs
            .contains(&("config-version".into(), "2026-08-05.1".into())));
    }

    /// ⭐ The roma halfway point renders a cache and says so, rather than rendering nothing.
    #[test]
    fn a_cache_only_plane_renders_a_cache_and_announces_it() {
        let doc = r#"{
          "protocol": "tbzl.buildconfig/v1", "config_version": "v", "tenant": "t", "plane": "roma",
          "facts": {"runner_label": "l", "cache": {"endpoint": "grpcs://cache.tbzl.dev:8980"},
            "auth": {"token_url": "https://t/", "scope": "s", "issuer": "i"}}
        }"#;
        let r = render(&profile(doc), "/t", "/h");
        assert!(r.bazelrc.contains("build --remote_cache=grpcs://cache.tbzl.dev:8980"));
        assert!(!r.bazelrc.contains("--remote_executor"));
        assert!(r.bazelrc.contains("SERVES CACHE ONLY"));
        assert!(r
            .env
            .contains(&("FASTVERK_TOKEN_FILE_CACHE_TBZL_DEV".into(), "/t".into())));
    }
}
