//! Turn a served profile into the artifacts a workflow consumes: one bazelrc, one set of
//! environment exports, one set of step outputs.
//!
//! ⭐ THE GENERATED BAZELRC IS THE WHOLE INTERFACE. Not a set of flags echoed into a shell
//! array, not `$RBE_ENDPOINT` for a later step to interpolate — a file, passed with
//! `bazel --bazelrc=<path>`. Three reasons, and the third is the one that matters:
//!
//!   1. It is diffable. Two builds that behaved differently can be compared directly.
//!   2. `--announce_rc` prints it into the build log, so the config is IN the evidence.
//!   3. ⛔ A shell variable can be overridden by a later step, silently, and a workflow that
//!      set `RBE_ENDPOINT` at job level would win. A file path cannot be half-overridden:
//!      either Bazel read this file or it did not.
//!
//! ⚠ `--bazelrc` is a STARTUP flag and must precede the command:
//! `bazel --bazelrc=<path> build //...`, never `bazel build --bazelrc=<path>`. Bazel's error
//! for the wrong order names the flag but not the position.

use crate::hostkey;
use crate::protocol::Profile;

/// Everything the Action writes out.
pub struct Rendered {
    /// Contents of the generated bazelrc.
    pub bazelrc: String,
    /// `$GITHUB_ENV` exports, in order.
    pub env: Vec<(String, String)>,
    /// `$GITHUB_OUTPUT` values.
    pub outputs: Vec<(String, String)>,
}

/// Render a profile.
///
/// `token_file` is where the workflow's token-minting step wrote the bearer. ⚠ The variable
/// NAME is derived here from the endpoint host; only the PATH comes from the caller. That
/// asymmetry is deliberate: the path is a local detail, the name is the thing that has to
/// agree with the endpoint and therefore must not be typed by a human.
pub fn render(profile: &Profile, token_file: &str, cred_helper: &str) -> Rendered {
    let mut rc = String::new();
    let f = &profile.facts;
    let r = &profile.recommendations;

    rc.push_str(&format!(
        "# GENERATED BY setup-tbzl — DO NOT EDIT, DO NOT COMMIT.\n\
         #\n\
         # tenant           {}\n\
         # plane            {}\n\
         # protocol         {}\n\
         # config_version   {}\n\
         #\n\
         # ⭐ Every value below was fetched from the platform at runtime. None of it is\n\
         # transcribed into the workflow, which is what makes the endpoint, the scope, the\n\
         # credential-helper host key and the exec-property token unable to drift apart:\n\
         # they have one source.\n\
         #\n\
         # ⭐ This is a VERSIONED recommendation, not a per-build decision. Every build that\n\
         # resolves config_version {} gets these exact bytes. That is what keeps two builds\n\
         # of one commit comparable and a regression bisectable.\n",
        profile.tenant, profile.plane, profile.protocol, profile.config_version,
        profile.config_version,
    ));
    if let Some(basis) = &r.basis {
        rc.push_str(&format!("#\n# basis: {basis}\n"));
    }
    rc.push('\n');

    // ── credential helper ────────────────────────────────────────────────────────────────
    rc.push_str(
        "# ⛔ HOST-KEYED, AND THE HELPER FAILS OPEN. A --credential_helper registered for the\n\
         # wrong host is never invoked for the right one, and the helper answers\n\
         # `{\"headers\":{}}` + exit 0 for any host it has no secret for — so Bazel sends NO\n\
         # Authorization header and the RBE answers UNAUTHENTICATED. The host below is derived\n\
         # from the endpoint above; setup-tbzl also PROBES the helper before the build starts,\n\
         # so an anonymous answer is a step failure rather than 97 failed targets.\n",
    );
    for host in profile.credential_hosts() {
        rc.push_str(&format!(
            "common --credential_helper={host}={cred_helper}\n"
        ));
    }
    rc.push('\n');

    // ── execution ────────────────────────────────────────────────────────────────────────
    if let Some(ex) = &f.execution {
        rc.push_str(&format!("build --remote_executor={}\n", ex.endpoint));
        if !ex.instance_name.is_empty() {
            rc.push_str(&format!(
                "# ⚠ NOT an isolation boundary — Buildbarn routes by PLATFORM, so two tenants\n\
                 # with different instance names share a CAS and share cache entries.\n\
                 build --remote_instance_name={}\n",
                ex.instance_name
            ));
        }
        rc.push_str(
            "# ⛔ BYTE-MATCHED AND PART OF THE ACTION DIGEST. The scheduler string-compares\n\
             # these against what its workers advertise and NEVER fetches the image named. A\n\
             # mismatch does not error: every action queues against an idle fleet. Measured\n\
             # once at 426 slots with ZERO demand and ~4s actions waiting ~40 minutes.\n",
        );
        for (k, v) in &ex.exec_properties {
            rc.push_str(&format!("build --remote_default_exec_properties={k}={v}\n"));
        }
        // ⛔ Emitted unconditionally when it is off, because the DEFAULT is off and an absent
        // flag would leave a repo-level `--remote_local_fallback` in force. Stating it is the
        // only way to be sure the mask is not on.
        if r.remote_local_fallback {
            rc.push_str("build --remote_local_fallback\n");
        } else {
            rc.push_str(
                "# ⛔⛔ THE MASK, EXPLICITLY OFF. With local fallback ON, a wrong exec property\n\
                 # does not queue — the build goes GREEN having run entirely on the runner, the\n\
                 # plane is unused, and the only symptom is that it was slow. Stated rather than\n\
                 # omitted so a repo-level --remote_local_fallback cannot leave it on.\n\
                 build --noremote_local_fallback\n",
            );
        }
    }

    // ── cache ────────────────────────────────────────────────────────────────────────────
    if let Some(c) = &f.cache {
        rc.push_str(&format!("build --remote_cache={}\n", c.endpoint));
    }
    if f.execution.is_none() {
        rc.push_str(
            "# ⭐ THIS PLANE SERVES CACHE ONLY — it declared no execution endpoint. Actions run\n\
             # LOCALLY on the runner and only their results are shared. That is a complete,\n\
             # legitimate answer (it is what roma serves today), and it is stated here so a\n\
             # slow build is not mistaken for a starved fleet.\n",
        );
    }

    // ── recommendations ──────────────────────────────────────────────────────────────────
    rc.push('\n');
    rc.push_str("# ── derived recommendations (config_version above) ──\n");
    if let Some(j) = r.jobs {
        rc.push_str(&format!(
            "# ⚠ Measured wrong in BOTH directions in one day on this estate: a 2-core runner's\n\
             # default of 2 capped REMOTE actions at 2 in flight, and 64 concurrent actions run\n\
             # LOCALLY on that same runner thrashed and OOMed. The right value is a property of\n\
             # where the actions execute, which is why the platform serves it.\n\
             build --jobs={j}\n"
        ));
    }
    if let Some(c) = r.remote_max_connections {
        rc.push_str(&format!(
            "# ⭐ THE BANDWIDTH KNOB. This estate measured 0.46 ms RTT but only 6.3 MB/s per\n\
             # stream, FLAT across four concurrent streams — per-stream throughput did not\n\
             # degrade as streams were added, so latency is not the constraint and aggregate\n\
             # throughput is linear in connection count over the measured range.\n\
             build --remote_max_connections={c}\n"
        ));
    }
    if let Some(t) = r.remote_timeout_seconds {
        rc.push_str(&format!("build --remote_timeout={t}\n"));
    }
    if let Some(d) = &r.remote_download {
        rc.push_str(&format!("build --remote_download_{d}\n"));
    }

    // ── env ──────────────────────────────────────────────────────────────────────────────
    let mut env = Vec::new();
    for host in profile.credential_hosts() {
        // ⭐ DERIVED, NEVER TYPED. See hostkey.rs — this single line is what makes a stale
        // helper key impossible rather than merely discouraged.
        env.push((hostkey::token_file_var(&host), token_file.to_string()));
    }
    // ⭐⭐ THE HOSTS THAT MUST AUTHENTICATE, FROM THE SAME LIST THE HOST KEY CAME FROM.
    //
    // `tomato-bazel/cred-helper` fails open: a miss yields `{"headers":{}}` and exit 0, so
    // Bazel sends no Authorization header and the far end answers UNAUTHENTICATED — a symptom
    // that names the endpoint rather than the credential. `FASTVERK_CRED_REQUIRE` turns a miss
    // into a non-zero exit FOR THESE HOSTS ONLY, which is safe precisely because anonymous is
    // a legitimate answer for a host nobody nominated and never for one somebody did.
    //
    // ⭐ Deriving it here rather than letting a workflow set it is the same property as the
    // token variable: the list of hosts that must authenticate cannot disagree with the list
    // of endpoints, because it IS that list.
    //
    // ⚠ HARMLESS ON AN OLDER HELPER. A binary predating the feature ignores the variable and
    // keeps failing open — at which point `verify::credential_round_trip` is still the check
    // that catches it. Defence in depth, in that order: the probe catches it before the build,
    // this catches it during one.
    let hosts = profile.credential_hosts();
    if !hosts.is_empty() {
        env.push(("FASTVERK_CRED_REQUIRE".into(), hosts.join(",")));
    }
    // ⭐⭐ THE TWO AUTH VALUES THE PLATFORM ALREADY KNOWS AND USED TO KEEP TO ITSELF.
    //
    // `facts.auth` has carried these since v1 of the protocol and NOTHING exported them, so every
    // consumer hard-coded them into its own token-minting step:
    //
    //   RBE_TOKEN_URL: https://tbzl-id-build-plane.auth.us-east-1.amazoncognito.com/oauth2/token
    //   RBE_TOKEN_SCOPE: fastverk-api/rbe:build
    //
    // ⛔ AND THEY ARE THE WORST TWO TO LEAVE TRANSCRIBED. The scope is STRING-MATCHED and the
    // issuer is checked, so a stale value does not error at mint time — it yields a token that
    // is well-formed, unexpired, and refused, and the build dies as UNAUTHENTICATED with a valid
    // token sitting on disk. That is the 97/97 failure this repository was written for, and it
    // was still reachable through the one door this Action did not cover.
    //
    // ⚠ Exported in BOTH phases. In `configure` they arrive too late to mint with and are simply
    // informational; in `resolve` they are the whole point. Emitting them unconditionally means
    // there is one code path, so the two phases cannot disagree about their values.
    env.push(("RBE_TOKEN_URL".into(), f.auth.token_url.clone()));
    env.push(("RBE_TOKEN_SCOPE".into(), f.auth.scope.clone()));
    env.push(("TBZL_CONFIG_VERSION".into(), profile.config_version.clone()));
    env.push(("TBZL_PLANE".into(), profile.plane.clone()));

    let mut outputs = vec![
        ("config-version".to_string(), profile.config_version.clone()),
        ("protocol".to_string(), profile.protocol.clone()),
        ("plane".to_string(), profile.plane.clone()),
        ("runner-label".to_string(), f.runner_label.clone()),
    ];
    if let Some(ex) = &f.execution {
        outputs.push(("endpoint".into(), ex.endpoint.clone()));
    }
    if let Some(j) = r.jobs {
        outputs.push(("jobs".into(), j.to_string()));
    }

    Rendered { bazelrc: rc, env, outputs }
}

/// Render the HOME bazelrc: the executor's storage layout, and nothing else.
///
/// ⭐⭐ WHY THIS FILE EXISTS SEPARATELY FROM THE GENERATED bazelrc. `--output_user_root` is a
/// STARTUP option, so it has to precede the verb on the command line — and so does `--bazelrc`.
/// That means the generated bazelrc only applies to invocations a workflow author remembered to
/// thread it through, and `bazel query` in some later step is exactly the one they forget. The
/// home bazelrc is read by bazel AUTOMATICALLY, on every invocation, in every step, with no
/// wrapper and no per-repo edit. That is the whole point: consumers stop transcribing this.
///
/// ⛔ SO IT CARRIES THE LAYOUT AND DELIBERATELY NOT THE PLANE CONFIG. A home rc is read AFTER
/// the repository's own `.bazelrc`, so anything here silently overrides a deliberate per-repo
/// setting. That hazard is real and this estate has already paid for it: a `--remote_cache` line
/// in a developer's `~/.bazelrc` split the cache and executor legs of an RBE build, and the
/// error named the SERVER's blobstore ("Shard 0: Object not found") for what was a client-side
/// misroute. Endpoint, credential helper and exec properties therefore stay in the explicit
/// `--bazelrc` file, where a repo can see and override them. Only storage locations — which no
/// repo sets deliberately, and which are properties of the machine rather than the build — go
/// here.
pub fn render_home(layout: &crate::layout::Layout, caches: &crate::protocol::Caches) -> String {
    let mut rc = String::new();
    rc.push_str(
        "# GENERATED BY setup-tbzl — DO NOT EDIT, DO NOT COMMIT.\n\
         #\n\
         # This file records WHERE THIS EXECUTOR KEEPS BAZEL STATE. It is written here, rather\n\
         # than passed with --bazelrc, because bazel reads the home rc on EVERY invocation —\n\
         # build, test, query, run, info, in any step — and the flags below are startup or\n\
         # near-startup options that a workflow would otherwise have to repeat at each call\n\
         # site. Missing one reopens a second output base in the container's writable layer.\n\
         #\n\
         # ⛔ It carries STORAGE LOCATIONS ONLY. A home rc overrides the repository's own\n\
         # .bazelrc, so the endpoint, credential helper and exec properties are deliberately\n\
         # NOT here — those stay in the bazelrc passed explicitly, where a repo can see them.\n\
         #\n\
         # Paths come from the RUNNER, not from the plane: see TBZL_CACHE_ROOT /\n\
         # TBZL_OUTPUT_ROOT. The plane chooses tiers; the host chooses places.\n\n",
    );

    match &layout.output_root {
        Some(o) => {
            rc.push_str(
                "# ⛔ THE OUTPUT BASE, AND IT MUST NOT BE ON THE SHARED VOLUME. Bazel locks it\n\
                 # exclusively, so two executors sharing one serialise rather than share. It\n\
                 # must equally not be left at bazel's default ($HOME/.cache/bazel), which in a\n\
                 # container is the writable layer that ephemeral-storage bounds — that evicted\n\
                 # every runner on this plane mid-build on 2026-08-19.\n",
            );
            rc.push_str(&format!("startup --output_user_root={}\n\n", o.display()));
        }
        // ⚠ SAY SO IN THE FILE. An absent line is indistinguishable from a line that was never
        // considered, and this is the one whose absence causes evictions.
        None => rc.push_str(
            "# ⚠ NO OUTPUT BASE CONFIGURED. TBZL_OUTPUT_ROOT was unset on this executor, so\n\
             # bazel will use its default under $HOME/.cache/bazel. That is fine on a laptop\n\
             # and wrong in a container, where it is the writable layer ephemeral-storage\n\
             # bounds. Set TBZL_OUTPUT_ROOT on the runner to fix it.\n\n",
        ),
    }

    let tiers: Vec<(bool, Option<std::path::PathBuf>, &str)> = vec![
        (caches.repository, layout.repository_cache(), "repository_cache"),
        (caches.repo_contents, layout.repo_contents_cache(), "repo_contents_cache"),
        (caches.disk, layout.disk_cache(), "disk_cache"),
    ];
    let mut wrote_any = false;
    for (enabled, path, flag) in tiers {
        // ⚠ Enabled-but-unrooted emits NOTHING rather than guessing a directory. A guessed
        // cache path is a cache nobody shares and nobody cleans.
        if let (true, Some(p)) = (enabled, path) {
            if !wrote_any {
                rc.push_str(
                    "# The shared, content-addressed tiers. Safe for concurrent readers and\n\
                     # writers by construction, which is what lets one volume serve every\n\
                     # executor on this host.\n",
                );
                wrote_any = true;
            }
            rc.push_str(&format!("build --{flag}={}\n", p.display()));
        }
    }
    if !wrote_any {
        rc.push_str(
            "# ⚠ NO SHARED CACHE CONFIGURED. TBZL_CACHE_ROOT was unset, so every build on this\n\
             # executor starts cold. Correct on a laptop; on a fleet it means the shared volume\n\
             # is not reaching the runner.\n",
        );
    }
    rc
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocol::Profile;

    fn profile(json: &str) -> Profile {
        Profile::parse(json.as_bytes()).expect("fixture parses")
    }

    const FULL: &str = r#"{
      "protocol": "tbzl.buildconfig/v1",
      "config_version": "2026-08-05.1",
      "tenant": "savvifi", "plane": "tbzl-build-plane",
      "facts": {
        "runner_label": "tbzl-linux-x64",
        "execution": {
          "endpoint": "grpcs://rbe.tbzl.dev:8980",
          "exec_properties": {"OSFamily": "linux", "container-image": "docker://x/y:z"},
          "advertised_platform": {"OSFamily": "linux", "container-image": "docker://x/y:z"}
        },
        "auth": {"token_url": "https://t/", "scope": "fastverk-api/rbe:build", "issuer": "https://i"}
      },
      "recommendations": {"jobs": 200, "remote_max_connections": 200}
    }"#;

    #[test]
    fn the_helper_host_comes_from_the_endpoint() {
        let r = render(&profile(FULL), "/tmp/tok", "/tmp/cred-helper");
        assert!(r
            .bazelrc
            .contains("common --credential_helper=rbe.tbzl.dev=/tmp/cred-helper"));
        assert!(r
            .env
            .contains(&("FASTVERK_TOKEN_FILE_RBE_TBZL_DEV".into(), "/tmp/tok".into())));
    }

    /// ⛔ The mask must be stated, not omitted — an absent flag leaves a repo-level
    /// `--remote_local_fallback` in force.
    #[test]
    fn local_fallback_is_stated_off_rather_than_left_unsaid() {
        let r = render(&profile(FULL), "/tmp/tok", "/h");
        assert!(r.bazelrc.contains("build --noremote_local_fallback"));
    }

    #[test]
    fn exec_properties_render_deterministically() {
        let a = render(&profile(FULL), "/t", "/h").bazelrc;
        let b = render(&profile(FULL), "/t", "/h").bazelrc;
        assert_eq!(a, b);
        // ⚠ BTreeMap orders by BYTE, not by a case-insensitive name: `O` (0x4F) sorts before
        // `c` (0x63), so `OSFamily` is emitted first. Pinned because the obvious
        // alphabetical reading is the opposite, and a rendering whose order silently flips
        // makes two bazelrc files un-diffable for no reason.
        let ci = a.find("container-image=docker://x/y:z").unwrap();
        let os = a.find("OSFamily=linux").unwrap();
        assert!(os < ci, "properties must be emitted in a stable, byte-ordered sequence");
    }

    /// ⭐ The require-list and the helper host come from ONE call, so they cannot disagree.
    #[test]
    fn the_hosts_that_must_authenticate_are_the_endpoints_themselves() {
        let r = render(&profile(FULL), "/tmp/tok", "/h");
        assert!(r
            .env
            .contains(&("FASTVERK_CRED_REQUIRE".into(), "rbe.tbzl.dev".into())));
    }

    #[test]
    fn config_version_is_recorded_for_the_build_record() {
        let r = render(&profile(FULL), "/t", "/h");
        assert!(r.bazelrc.contains("config_version   2026-08-05.1"));
        assert!(r.env.contains(&("TBZL_CONFIG_VERSION".into(), "2026-08-05.1".into())));
        assert!(r
            .outputs
            .contains(&("config-version".into(), "2026-08-05.1".into())));
    }

    /// ⭐ The roma halfway point renders a cache and says so, rather than rendering nothing.
    #[test]
    fn a_cache_only_plane_renders_a_cache_and_announces_it() {
        let doc = r#"{
          "protocol": "tbzl.buildconfig/v1", "config_version": "v", "tenant": "t", "plane": "roma",
          "facts": {"runner_label": "l", "cache": {"endpoint": "grpcs://cache.tbzl.dev:8980"},
            "auth": {"token_url": "https://t/", "scope": "s", "issuer": "i"}}
        }"#;
        let r = render(&profile(doc), "/t", "/h");
        assert!(r.bazelrc.contains("build --remote_cache=grpcs://cache.tbzl.dev:8980"));
        assert!(!r.bazelrc.contains("--remote_executor"));
        assert!(r.bazelrc.contains("SERVES CACHE ONLY"));
        assert!(r
            .env
            .contains(&("FASTVERK_TOKEN_FILE_CACHE_TBZL_DEV".into(), "/t".into())));
    }
}

/// Fences around the block setup-tbzl owns inside `$HOME/.bazelrc`.
///
/// ⛔ THE FILE IS NOT OURS TO REPLACE, AND THAT IS NOT HYPOTHETICAL IN EITHER DIRECTION. A
/// developer's `~/.bazelrc` on this estate carried a `--remote_cache` line that split the cache
/// and executor legs of an RBE build and cost an afternoon — so its contents matter. And a
/// GITHUB-HOSTED RUNNER SHIPS ITS OWN `~/.bazelrc`: an earlier version of this code refused to
/// touch a file it had not written, which failed setup-tbzl's own CI on the first hosted run
/// and would have failed every consumer on a hosted runner.
///
/// So: own a fenced block, rewrite only that block, leave everything else byte-identical, and
/// be idempotent across re-runs.
pub const BLOCK_BEGIN: &str = "# >>> setup-tbzl layout >>>";
pub const BLOCK_END: &str = "# <<< setup-tbzl layout <<<";

/// Flags whose meaning setup-tbzl owns. An existing line setting one of these OUTSIDE our block
/// is a real conflict — the home rc is read after the repo's `.bazelrc`, so whichever of us
/// wins, the other's intent is silently discarded.
pub const OWNED_FLAGS: &[&str] =
    &["output_user_root", "repository_cache", "repo_contents_cache", "disk_cache"];

/// Replace (or append) our fenced block inside `prev`, leaving the rest untouched.
pub fn splice_block(prev: &str, block: &str) -> Result<String, String> {
    // Drop any previous block of ours first, so re-running is idempotent rather than additive.
    let (before, after) = match (prev.find(BLOCK_BEGIN), prev.find(BLOCK_END)) {
        (Some(a), Some(b)) if b > a => (&prev[..a], &prev[b + BLOCK_END.len()..]),
        // ⚠ A begin without an end means someone edited inside the fences and truncated them.
        // Rewriting from a guessed boundary could delete their lines, so stop instead.
        (Some(_), _) => {
            return Err(format!(
                "$HOME/.bazelrc contains `{BLOCK_BEGIN}` with no matching `{BLOCK_END}`. The \
                 block setup-tbzl owns cannot be located, and guessing where it ends risks \
                 deleting lines that are not ours. Repair or remove the fences by hand"
            ))
        }
        _ => (prev, ""),
    };

    let foreign = format!("{before}{after}");

    // ⛔ A CONFLICT IS "WE BOTH SET IT", NOT "YOU SET IT" — AND GETTING THAT WRONG BROKE THIS
    // ACTION'S OWN CI. A GitHub-hosted runner's ~/.bazelrc ships
    // `common --repository_cache=/home/runner/.cache/bazel-repo`; on that runner TBZL_CACHE_ROOT
    // is unset, so the block below contains NO cache lines and there is nothing to fight over.
    // Checking the whole owned-flag list regardless of what we emit failed every hosted
    // consumer over a flag setup-tbzl was not setting.
    //
    // So the owned set is derived from the block we are about to write. Only a flag present on
    // BOTH sides can silently discard someone's intent, and only that is fatal.
    let emitting: Vec<&&str> = OWNED_FLAGS.iter().filter(|f| block.contains(**f)).collect();
    for flag in emitting {
        for line in foreign.lines() {
            let l = line.trim();
            // ⚠ A commented-out flag is not a conflict; refusing on it would fail any file whose
            // author documented the option, which is common and harmless.
            if !l.starts_with('#') && l.contains(*flag) {
                return Err(format!(
                    "$HOME/.bazelrc already sets `{flag}` outside setup-tbzl's block:\n    {l}\n\
                     setup-tbzl is also setting it from the runner's layout, and a home bazelrc \
                     overrides the repository's own .bazelrc — so one of the two settings would \
                     silently lose. Remove that line, or pass --no-home-bazelrc and configure \
                     the layout yourself"
                ));
            }
        }
    }

    let mut out = foreign.trim_end().to_string();
    if !out.is_empty() {
        out.push_str("\n\n");
    }
    out.push_str(BLOCK_BEGIN);
    out.push('\n');
    out.push_str(block.trim_end());
    out.push('\n');
    out.push_str(BLOCK_END);
    out.push('\n');
    Ok(out)
}

#[cfg(test)]
mod home_rc_tests {
    use super::*;

    /// ⛔ THE FAILURE THAT BROKE THIS ACTION'S OWN CI. A GitHub-hosted runner SHIPS a
    /// `~/.bazelrc`. An earlier version refused to touch any file it had not written, which
    /// failed on the first hosted run and would have failed every consumer on a hosted runner.
    /// Pre-existing content must survive byte-for-byte.
    #[test]
    fn a_pre_existing_home_bazelrc_survives_intact() {
        let prev = "build --announce_rc\nbuild --color=yes\n";
        let out = splice_block(prev, "startup --output_user_root=/w/.bazelroot").unwrap();
        assert!(out.contains("build --announce_rc"), "foreign line was lost:\n{out}");
        assert!(out.contains("build --color=yes"), "foreign line was lost:\n{out}");
        assert!(out.contains("startup --output_user_root=/w/.bazelroot"));
    }

    /// ⚠ IDEMPOTENT. setup-tbzl runs at the head of every job, and on a runner with a persistent
    /// home an additive write would grow the file without bound and leave STALE paths above the
    /// current ones — where, bazelrc being last-wins, the newest would win by luck of ordering.
    #[test]
    fn re_running_replaces_the_block_rather_than_appending() {
        let prev = "build --color=yes\n";
        let once = splice_block(prev, "startup --output_user_root=/a").unwrap();
        let twice = splice_block(&once, "startup --output_user_root=/b").unwrap();
        assert_eq!(twice.matches(BLOCK_BEGIN).count(), 1, "block duplicated:\n{twice}");
        assert!(!twice.contains("/a"), "the stale path survived:\n{twice}");
        assert!(twice.contains("/b"));
        assert!(twice.contains("build --color=yes"), "foreign line lost on re-run");
        // And a third run with identical input is a no-op.
        let thrice = splice_block(&twice, "startup --output_user_root=/b").unwrap();
        assert_eq!(twice, thrice, "not stable: a no-op run changed the file");
    }

    /// ⛔ A REAL CONFLICT IS FATAL. The home rc overrides the repository's own .bazelrc, so if
    /// someone already set a flag we manage, one of the two intents is discarded silently.
    #[test]
    fn a_conflicting_flag_outside_the_block_is_refused() {
        let prev = "build --disk_cache=/somewhere/else\n";
        let err = splice_block(prev, "build --disk_cache=/bazel-cache/disk").unwrap_err();
        assert!(err.contains("disk_cache"), "the error must name the flag, got: {err}");
    }

    /// ⚠ A COMMENTED-OUT FLAG IS NOT A CONFLICT. Refusing on it would fail on any file whose
    /// author documented the option, which is common and harmless.
    #[test]
    fn a_commented_flag_is_not_a_conflict() {
        let prev = "# build --disk_cache=/somewhere/else\n";
        assert!(splice_block(prev, "build --disk_cache=/x").is_ok());
    }

    /// ⚠ TRUNCATED FENCES STOP RATHER THAN GUESS. Rewriting from a guessed boundary could
    /// delete lines that are not ours.
    #[test]
    fn an_unterminated_block_is_refused_rather_than_repaired() {
        let prev = format!("{BLOCK_BEGIN}\nstartup --output_user_root=/a\n");
        let err = splice_block(&prev, "startup --output_user_root=/b").unwrap_err();
        assert!(err.contains("no matching"), "got: {err}");
    }

    /// An empty/absent home rc is the ordinary laptop case.
    #[test]
    fn an_absent_file_just_gets_the_block() {
        let out = splice_block("", "startup --output_user_root=/w").unwrap();
        assert!(out.starts_with(BLOCK_BEGIN), "got:\n{out}");
        assert!(out.trim_end().ends_with(BLOCK_END));
    }
}

#[cfg(test)]
mod home_rc_conflict_scope_tests {
    use super::*;

    /// ⛔ THE SECOND FAILURE THIS ACTION'S OWN CI CAUGHT. A GitHub-hosted runner's ~/.bazelrc
    /// ships `common --repository_cache=/home/runner/.cache/bazel-repo`. On that runner
    /// TBZL_CACHE_ROOT is unset, so setup-tbzl emits no cache lines at all — there is nothing to
    /// conflict with. An earlier version checked the whole owned-flag list regardless of what it
    /// was writing and failed every hosted consumer over a flag it was not setting.
    #[test]
    fn a_flag_we_are_not_emitting_is_not_a_conflict() {
        let prev = "common --repository_cache=/home/runner/.cache/bazel-repo\n";
        // The block a runner with no TBZL_CACHE_ROOT produces: output base only.
        let out = splice_block(prev, "startup --output_user_root=/w/.bazelroot")
            .expect("no cache lines emitted, so the runner's own repository_cache is not a conflict");
        assert!(out.contains("common --repository_cache="), "the runner's line must survive");
    }

    /// ⛔ BUT THE SAME FILE IS FATAL ONCE WE DO EMIT THAT FLAG — otherwise one of two deliberate
    /// settings silently loses, and a home rc beats the repository's own .bazelrc.
    #[test]
    fn the_same_line_is_a_conflict_once_we_emit_that_flag() {
        let prev = "common --repository_cache=/home/runner/.cache/bazel-repo\n";
        let err = splice_block(prev, "build --repository_cache=/bazel-cache/repo")
            .expect_err("both sides setting repository_cache must be fatal");
        assert!(err.contains("repository_cache"), "the error must name the flag, got: {err}");
    }
}

#[cfg(test)]
mod auth_export_tests {
    use super::*;
    use crate::protocol::Profile;

    /// ⛔ THE TWO VALUES EVERY CONSUMER USED TO HARD-CODE.
    ///
    /// `facts.auth` carried them from the first version of the protocol and nothing exported
    /// them, so each repo transcribed them into its own minting step. They are the worst two to
    /// leave transcribed: the scope is string-matched, so a stale one yields a token that is
    /// well-formed, unexpired and REFUSED — the build dies as UNAUTHENTICATED with a valid token
    /// on disk.
    #[test]
    fn the_auth_values_are_exported_for_the_minting_step() {
        let p = Profile::parse(crate::protocol::SAMPLE.as_bytes()).unwrap();
        let r = render(&p, "/tmp/tok", "/usr/local/bin/cred-helper");
        let get = |k: &str| r.env.iter().find(|(n, _)| n == k).map(|(_, v)| v.clone());
        assert_eq!(
            get("RBE_TOKEN_URL").as_deref(),
            Some("https://x.example/oauth2/token"),
            "RBE_TOKEN_URL must be exported or the minting step has to hard-code it"
        );
        assert_eq!(
            get("RBE_TOKEN_SCOPE").as_deref(),
            Some("fastverk-api/rbe:build"),
            "RBE_TOKEN_SCOPE must be exported — a stale scope mints a token that is refused"
        );
    }
}
